name: movie-catalog
recipe: drupal9
config:
  php: '8.1'
  composer_version: '2.2.12'
  via: apache:2.4
  webroot: web/
  database: mysql
  drush: true
  xdebug: false

plugins:
  "@lando/drupal/": ./../../
