_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: f3752dea-0770-4c27-a90c-cb622cbd061c
name: 'Movie Catalog'
mail: admin@example.com
slogan: 'Not just another catalog!'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
